### ISSUE TITLE
moveFinishedBackup: ENOENT: no such file or directory, stat 'D:\backup-joplin\joplin_active_backup_job'

### ISSUE THREAD

**Issue by tuaone** [JackGruber/joplin-plugin-backup#13]
I have error as below
moveFinishedBackup: ENOENT: no such file or directory, stat 'G:\backup-joplin\joplin_active_backup_job'
- and plugin does not automatically delete existing directory. plugin does not delete the . inside empty folder
i configuration " keep x backup " = 3 .
 ( 5 folders, there are 2 empty folders. but it doesn't delete 2 empty folders ) 
![backup](https://user-images.githubusercontent.com/59154355/125556204-125c1dfd-b14d-486f-b087-5b12d27ca40f.JPG)

thanks you

**Comment by JackGruber** [comment]
The backup was not completed without error, therefore the backup retention was not executed. 

- Which version of the plugin do you use?
- Could you post all your settings
- Could you please set Logfile to `Verbose` and poste the logfile
  When the logfile is not in your backup target, please check `~\.config\joplin-desktop\cache\io.github.jackgruber.backup`

**Comment by tuaone** [comment]
Which version of the plugin do you use? Simple Backup v1.0.1
![y8](https://user-images.githubusercontent.com/59154355/125577193-425f1643-37b2-493c-858c-ce28a06774ee.JPG)
![uiui](https://user-images.githubusercontent.com/59154355/125577217-6b0590b9-1603-49f0-b1cd-3c2b3fd61e6d.JPG)
![y8](https://user-images.githubusercontent.com/59154355/125577220-1380845c-03c5-476f-9e92-fc640baecccf.JPG)
can't see logfile 
![lo](https://user-images.githubusercontent.com/59154355/125577356-84c3d5c4-a5ee-4f35-bbfa-932c940e952d.JPG)

**Comment by JackGruber** [comment]
Please set the Log to `Verbose`and post the logfile.
![grafik](https://user-images.githubusercontent.com/24863925/125593912-7cb5a857-c47b-45a5-964f-fd3b688d412b.png)

Hm the path from the error message does not match any of the configured. Have you changed the configuration in the meantime and if so the same error still occurs?

**Comment by tuaone** [comment]
no logfile
![5t](https://user-images.githubusercontent.com/59154355/126031451-d856ac26-0dff-43b0-8595-7f144c82d1b4.JPG)
![5y](https://user-images.githubusercontent.com/59154355/126031454-552ad3e1-995a-4f42-903f-64865516879e.JPG)

**Comment by JackGruber** [comment]
The logfile should be stored in `%userprofile%\.config\joplin-desktop\cache\io.github.jackgruber.backup`

**Comment by tuaone** [comment]
https://user-images.githubusercontent.com/59154355/126046378-5a0484ef-3cee-4ca1-a762-df0872026ae8.mp4
you can see this video. i don't see logfile

**Comment by JackGruber** [comment]
What is in your `D:\FFCache\` ?

**Comment by tuaone** [comment]
this is temporary export path .
today i have error
moveFinishedBackup: EPERM: operation not permitted, copyfile

**Comment by JackGruber** [comment]
`moveFinishedBackup: EPERM: operation not permitted, copyfile`  eans the script has no authorization/possibility to copy the data to the destination folder. But it may also have something to do with the `Temporary eport path`, so set this to nothing for testing. 

Did you set the logfiles to verbos? The logfile is created immediately after the start of the backup and remains in case of an error. Only if the backup was successful, it is moved to the target directory.

**Comment by tuaone** [comment]
i set logfiles to verbos. but i don't see logfile  ( \cache\io.github.jackgruber.backup )

**Comment by harun27** [comment]
Hi @JackGruber ,
I have the same problem like @tuaone but with the log file. So my settings are like:

![Screenshot 2021-10-06 133330](https://user-images.githubusercontent.com/53127830/136195143-5e44f891-8a64-4663-a140-143dc9bf47ad.png)

This is the folder where I want to do the backup:

![Screenshot 2021-10-06 133415](https://user-images.githubusercontent.com/53127830/136195206-91912f6f-be6e-4c6b-8f3b-a4bd777f32eb.png)

The backups in that folder are old backups. The error message is like this:

![Screenshot 2021-10-06 133454](https://user-images.githubusercontent.com/53127830/136195348-82fa3b11-a3cd-4cf9-8ccc-1e8c50eeb751.png)

The created backups are still in the temp folder and are not moved to my desired backup folder. Look:

![Screenshot 2021-10-06 133505](https://user-images.githubusercontent.com/53127830/136195481-3d0fdaf5-7a76-4264-ac74-612988bb962c.png)

Here is also my log file:

[activeBackup.log](https://github.com/JackGruber/joplin-plugin-backup/files/7293349/activeBackup.log)
