### ISSUE TITLE
Error message while creating backup (but backup file seems to be ok...)

### ISSUE THREAD

**Issue by antoniopaolini** [JackGruber/joplin-plugin-backup#14]
Hello, 
today I received this error.
![image](https://user-images.githubusercontent.com/60228211/125593134-9cc7f2e6-c7a4-4073-9b77-8efa49c3368f.png)
The logfile don't add any info (it' is set to "error", but now I set loglevel to verbose, for the next error, if it came).

I see that the backup file was created but the name is strange: there's double extension:
![image](https://user-images.githubusercontent.com/60228211/125595823-f3d09179-2685-4c60-8b9f-45596c0aabe6.png)

The Plugin version is 1.0.1.
Joplin 2.1.8 (prod, win32)

**Comment by JackGruber** [comment]
Hm intresting `The file is used by another process` ... but the filename strange.
Did you create a manual backup or was this from a automatic backup?

**Comment by antoniopaolini** [comment]
Automatic backup. The destination is a mapped network disc (y:\...etc.etc..).
I don't know where the plugin's setting is saved but if you want I can send you a screenshot.

**Comment by JackGruber** [comment]
Could you please set the Log to verbose and post the log when the error occurse.

**Comment by antoniopaolini** [comment]
Hello.
The problem no longer occurred, but today I found new problem (https://github.com/JackGruber/joplin-plugin-backup/issues/21#issue-976875251)
