### ISSUE TITLE
moveFinishedBackup: EPERM: operation not permitted, rename...

### ISSUE THREAD

**Issue by blank15927** [JackGruber/joplin-plugin-backup#16]
Joplin 2.2.1 (prod, win32) 
Windows 10 21H1
Simple Backup v1.0.1

I have this error message popping up regularly.

![Error](https://imgur.com/3kZSfrF.jpg)

It doesn't seem to have any impact on the backup itself. As far as I can tell, despite this message, backups are fine.

I found out a pattern when the message pops up. It happens :
- when I start my computer in the morning
or
- when the computer comes out of sleep mode

These are the only times when this message appears as soon as I click the Joplin icon in the notification area. Other thant that, the rest of  the time,  the plugin run silently as expected without any error message.

Here are my plugin settings and the backup log file (verbose mode).

[backup.log](https://github.com/JackGruber/joplin-plugin-backup/files/6835786/backup.log)

![Settings](https://imgur.com/RDRW1u0.jpg)

**Comment by JackGruber** [comment]
Ah I see your problem, there are two running backuptasks, so one job cannot rename the folder

**Comment by blank15927** [comment]
> Do you use a portable version of Joplin?

Yes, I do.

**Comment by JackGruber** [comment]
Could you please test the `v1.0.2`

**Comment by blank15927** [comment]
Just installed. I'll let you know if the message pops up again.

Thanks !

**Comment by blank15927** [comment]
So, a few days later... everything's fine. No more error messages.
Thanks again .

**Comment by pmmontanari** [comment]
Hello, I am getting this error as I have two Joplin instances with two different profiles open. The backup of the second instance always fails as the first instance is doing the first.
