### ISSUE TITLE
Button to backup now

### ISSUE THREAD

**Issue by jesusdeveloper** [JackGruber/joplin-plugin-backup#27]
Hello!

The plugin is fantastic, congratulations, a great plugin for Joplin, much needed!
It has many options, although I would like to have a button that allows you to make a backup now. That is, I make some configurations and when I click the button, the copy begins immediately.

Is this possible?

Thanks!

**Comment by JackGruber** [comment]
Is already implemented.
![grafik](https://user-images.githubusercontent.com/24863925/141642152-86e76bcd-5567-4abc-a83e-19311e0ea48c.png)

**Comment by jesusdeveloper** [comment]
Sorry! I didn't see!! :O
