### ISSUE TITLE
Cloning settings

### ISSUE THREAD

**Issue by Rolograaf** [JackGruber/joplin-plugin-backup#30]
This is not a feature request or bug report, I was wondering if it was possible to transfer settings from my personal Joplin to my at work Joplin. They use different network store, pre-release vs secure release, but I would like an easy way to get the userchrome and usersettings including fonts, plug-ins and other interface settings backed-up and restored from one to the other?

**Comment by JackGruber** [comment]
You can copy your `keymap-desktop.json`, `userchrome.css`, `userstyle.css` and `plugins` folder. 
But not the `settings.json` without editing. Therefore, a simple transfer of the settings is not possible. Also the plugin settings can not be transferred at the moment.
