### ISSUE TITLE
jexExport Error

### ISSUE THREAD

**Issue by jmquigley** [JackGruber/joplin-plugin-backup#35]
I recently updated to Joplin 2.7.13 (prod, win32) (windows 10).  I now receive the following error when the backup is executed:

![image](https://user-images.githubusercontent.com/1438376/155853984-99fc6b04-9c55-49c1-ad8c-5f256d7a8c82.png)

And no backup is created.  Using "Simple Backup v1.0.5".

**Comment by JackGruber** [comment]
Is fixed with Joplin [2.7.14](https://github.com/laurent22/joplin/releases/tag/v2.7.14)
