### ISSUE TITLE
Cannot use 'in' operator to search for 'is_shared' in undefined

### ISSUE THREAD

**Issue by JakubS83** [JackGruber/joplin-plugin-backup#36]
Hello All,
I have a Issue with the backup:
Backup plugin
jexExport: Cannot use 'in' operator to search for 'is_shared' in undefined

Backup error

Could you help me?
Joplin version: 2.7.13
Backup version: 1.0.5
OS: Windows 10

**Comment by JackGruber** [comment]
Please update you Joplin installation, this is a Bug in `2.7.13`

https://github.com/JackGruber/joplin-plugin-backup/issues/35
https://github.com/laurent22/joplin/issues/6203

**Comment by JakubS83** [comment]
Hello Jack,
thank you for your reply.
Regards Jakub

út 1. 3. 2022 v 15:57 odesílatel JackGruber ***@***.***>
napsal:
