### ISSUE TITLE
Warning for first time usage of a path

### ISSUE THREAD

**Issue by JackGruber** [JackGruber/joplin-plugin-backup#39]
Warn the user that all files not releated to the backup in this folder would be deleted. 

- [ ] Show Msg on path change
- [ ] Don't show Msg for already setuped / installed plugin
- [ ] Add a more clear warning in the documentation
- [ ] Add a information in the plugin configuration

**Comment by ScriptInfra** [comment]
@JackGruber - Is this still the case, where all files in the backup directory are deleted? I have not been able to replicate this on Fedora Linux.

I created a testdir and created a test file, and then ran the backup, which did not seem to remove the test file:

[root@workstation testdir]# ls -ltrh
total 40K

-rw-r--r--. 1 workstation workstation   0 May 29 16:42 test.txt
drwxr-xr-x. 3 workstation workstation 36K May 29 16:46 joplin_backup_05M.29D.2022Y.16H.46M

**Comment by JackGruber** [comment]
Changes will be published with the next version
