### ISSUE TITLE
proper directory selector instead a plain text input if possible

### ISSUE THREAD

**Issue by alexanderadam** [JackGruber/joplin-plugin-backup#4]
This would probably help to avoid errors and [should be working in webkit based browsers and even Firefox](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory):

```html
<input type="file" id="directory" name="directory" webkitdirectory directory />
```

I'm not sure whether this would work here but it would be great if it does.

**Comment by JackGruber** [comment]
Unfortunately no, only the GUI API functions which Joplin offers are available. Especially with in the settings.
