### ISSUE TITLE
backup won't work if old newJoplinBackup.7z file is there

### ISSUE THREAD

**Issue by th-ros** [JackGruber/joplin-plugin-backup#40]
Hello,
today I recognized that no backups were created if the file `newJoplinBackup.7z` is still in the backup directory.

My Joplin is running all the time on my Notebook and I made backups every hour on a network drive. Today I recognized the file `newJoplinBackup.7z` in the backup directory which was many days old an since this date no backups were made anymore.

After some tests I found the solution: I removed the file and everything works fine.

So I think this is a bug and should be solved. I think the old `newJoplinBackup.7z` was the result of a interuppted backup by a shutdown during the backup was running.

Greeting and thx for the nice plugin, Thomas

**Comment by th-ros** [comment]
My backup settings are these. Drive h:\ is a network drive.
![my Joplin backup settings](https://user-images.githubusercontent.com/74838904/178458238-f21cb4ee-720a-43bb-93b5-5eef77344d20.PNG)

**Comment by JackGruber** [comment]
Ok, tnx. I try to replicate it with this settings.

**Comment by JackGruber** [comment]
The behavior that the backup does not run if the newJoplinBackup.7z already exists in the backup directory I could not reproduce. But I have found a other bug during the investigation. 
If the file was existing from a privues aborted backup, the  newly created backup could then contain old and new backup data.
To prevent this the file is now deleted to the begin.
