### ISSUE TITLE
Enhancement Request: Add Backup Location option to ssh

### ISSUE THREAD

**Issue by ScriptInfra** [JackGruber/joplin-plugin-backup#41]
I think there is a valid use case to want to make all backups to a server using ssh. Would it be possible to add this option to the 'Backup path'?

For example, Deja Dup provides the following backup target options:

![image](https://user-images.githubusercontent.com/63025323/170890326-a119773a-678b-450d-8cc7-abc6bf0a91f2.png)

**Comment by JackGruber** [comment]
Currently there is no plan to support other storage providers.
