### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Anzar-Makrani** [JackGruber/joplin-plugin-backup#44]
I installed the extension from the Joplin app and manually but there is no backup tab in the options menu.
I use archcraft Linux.

![Screenshot_2022-07-26-20-08-24_1680x1050](https://user-images.githubusercontent.com/73460385/181035841-364826c7-7a7a-4179-9ffc-f646d4c9252e.png)

uname -r  = `5.18.14-arch1-1`

**Comment by JackGruber** [comment]
Which Joplin version are you using? 
Can you please post a debug log of Joplin and the output of the console
https://joplinapp.org/debugging/

**Comment by Anzar-Makrani** [comment]
> Which Joplin version are you using? Can you please post a debug log of Joplin and the output of the console https://joplinapp.org/debugging/

2.8.8-1

**Comment by JackGruber** [comment]
I can see the plugin is loaded, but no `joplin.plugins: "Starting plugin`
```
2022-07-27 14:54:43: PluginService: "Loading plugin from /home/wg/.config/joplin-desktop/cache/io.github.jackgruber.backup"
```

Yesterday your database was read only according to the logs, maybe the plugin enabling was not saved. Could you disable the plugin, restart joplin, enable the plugin and restart Joplin and check if the plugin is appears.

When not, please post the console output!

**Comment by Anzar-Makrani** [comment]
> I can see the plugin is loaded, but no `joplin.plugins: "Starting plugin`
> 
> ```
> 2022-07-27 14:54:43: PluginService: "Loading plugin from /home/wg/.config/joplin-desktop/cache/io.github.jackgruber.backup"
> ```
> 
> Yesterday your database was read only according to the logs, maybe the plugin enabling was not saved. Could you disable the plugin, restart joplin, enable the plugin and restart Joplin and check if the plugin is appears.
> 
> When not, please post the console output!

Well I did enable and disable the plugin within the gui app and also reinstall it several time both manually and from the plugin tab but it didn't appear thats why I open a issue here.


_I'm going to  try to install joplin and plugin  in a live linux environment to see if something wrong with my install._

**Comment by Anzar-Makrani** [comment]
> > I can see the plugin is loaded, but no `joplin.plugins: "Starting plugin`
> > ```
> > 2022-07-27 14:54:43: PluginService: "Loading plugin from /home/wg/.config/joplin-desktop/cache/io.github.jackgruber.backup"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Yesterday your database was read only according to the logs, maybe the plugin enabling was not saved. Could you disable the plugin, restart joplin, enable the plugin and restart Joplin and check if the plugin is appears.
> > When not, please post the console output!
> 
> Well I did enable and disable the plugin within the gui app and also reinstall it several time both manually and from the plugin tab but it didn't appear thats why I open a issue here.
> 
> _I'm going to try to install joplin and plugin in a live linux environment to see if something wrong with my install._

I'm so sorry

**Comment by paulelms** [comment]
Faced same problem in archlinux, all other plugins are installed and working
