### ISSUE TITLE
Backup fails to delete previous backup file

### ISSUE THREAD

**Issue by bladewolf55** [JackGruber/joplin-plugin-backup#45]
Simple Backup: 1.1.0
OS: Windows 11 Pro
Joplin: 2.9.1 (prod, win32)

## Issue
Consistently, when I open Joplin, I get a message that a previous backup file doesn't exist when it does.

![image](https://user-images.githubusercontent.com/2903411/181056024-3c226853-f4ad-46e5-ae2b-d6cb1bcaedb4.png)

## More Information
This started happening a few weeks ago, prior to updating to Simple Backup 1.1.0, so I don't think it's a Simple Backup version issue. 

I've tried the following:

1. Set the entire Joplin Backup folder to allow offline access
2. Restart Joplin and manually ran backup

I may have had a false negative with number 2. I assumed that, when running a manual backup, older backups would be deleted. But I can't confirm if that's the expected behavior. The reason I wanted to run that test is in case Joplin is starting *before* Google Drive and is capturing file system information early. In short, maybe Joplin doesn't believe the G drive exists. Or, maybe SB doesn't.

**Comment by JackGruber** [comment]
Hm I'm not sure if this has todo with the G drive and how it handles the files in the file system. 
The G Drive is accessible, because a new backup is created and the old backup set would be deleted after the creation. 
The Files reald offline accessible, because the other files have a cloud symbol.

**Comment by bladewolf55** [comment]
I just did a bunch more thorough testing. Conclusions and tests below. What
other troubleshooting do you suggest? Is there debug logging I can enable?


*Conclusions*

   - Joplin or SB incorrectly stores the backup path when entered directly
   into the text control. (Works correctly using the Browse button.
   - Joplin or SB incorrectly displays the backup path when it contains
   spaces.
   - Deleting old backup sets isn't working regardless of path. (Google
   Drive is not the problem, nor is spaces in the path.)

*SB Config*
[image: image.png]

Backup Info:

[{"name":"20220713-1041.7z","date":1657730443323},{"name":"20220717-1812.7z","date":1658103122905},{"name":"20220718-0930.7z","date":1658158191828},{"name":"20220719-1020.7z","date":1658247590005},{"name":"20220720-1024.7z","date":1658334229471},{"name":"20220721-1024.7z","date":1658420663602},{"name":"20220721-1043.7z","date":1658421806451},{"name":"20220721-1416.7z","date":1658434564894},{"name":"20220722-0708.7z","date":1658495298124},{"name":"20220723-1525.7z","date":1658611519524},{"name":"20220724-0635.7z","date":1658666067405},{"name":"20220726-1000.7z","date":1658851196577},{"name":"20220726-1045.7z","date":1658852847081},{"name":"20220726-1103.7z","date":1658854914269},{"name":"20220726-1223.7z","date":1658859757871},{"name":"20220726-1226.7z","date":1658859945446}]

*Tests*

   - A simple Joplin quit/restart today, got the same backup error message.
   - Quit > set all files to offline access > restart. Same error.

I was going to try changing the backup path, and when I checked Backup
settings I saw this:

[image: image.png]

However, the SQLite settings table does have the correct value:

[image: image.png]

So, test steps.

   1. Copy all backups to  C:\Users\charl\Downloads\Joplin Backup
   2. In Joplin, change backup path using copy/paste
   to C:\Users\charl\Downloads\Joplin Backup
   3. Quit and restart
   4. Check how path is displayed. OK.
   [image: image.png]
   5. Wait for on-startup backup. Get bizarre error message. What's with
   that path?
   [image: image.png]
   6. What's in the database?
   [image: image.png]
   7. On a whim, tried browsing to the backup folder and selecting it. This
   resulted, again, in the truncated path displayed. Database value is correct.
   [image: image.png]
   8. Renamed the backup folder, removing spaces. Pasted in the new path.
   The path displays correctly, but is stored wrong.
   [image: image.png]
   [image: image.png]
   9. Use the Browse button to select the path. This time all is correct.
   [image: image.png]

   10. Quit/restart. Same error!
   [image: image.png]


--
Charles L Flatt
"If my life wasn't funny it would just be true, and that is unacceptable."
--Carrie Fisher

**Comment by bladewolf55** [comment]
(Repost to include the images directly. Email replied don't support Markdown.)

I just did a bunch more thorough testing. Conclusions and tests below. What
other troubleshooting do you suggest? Is there debug logging I can enable?

(Updated to include images.)

**Conclusions**

   - Joplin or SB incorrectly stores the backup path when entered directly
   into the text control. (Works correctly using the Browse button.
   - Joplin or SB incorrectly displays the backup path when it contains
   spaces.
   - Deleting old backup sets isn't working regardless of path. (Google
   Drive is not the problem, nor is spaces in the path.)

**SB Config**
![image](https://user-images.githubusercontent.com/2903411/181092053-95ad63b8-f034-4a81-b1f2-b08e86f4ac8e.png)

Backup Info:

```text
[{"name":"20220713-1041.7z","date":1657730443323},{"name":"20220717-1812.7z","date":1658103122905},{"name":"20220718-0930.7z","date":1658158191828},{"name":"20220719-1020.7z","date":1658247590005},{"name":"20220720-1024.7z","date":1658334229471},{"name":"20220721-1024.7z","date":1658420663602},{"name":"20220721-1043.7z","date":1658421806451},{"name":"20220721-1416.7z","date":1658434564894},{"name":"20220722-0708.7z","date":1658495298124},{"name":"20220723-1525.7z","date":1658611519524},{"name":"20220724-0635.7z","date":1658666067405},{"name":"20220726-1000.7z","date":1658851196577},{"name":"20220726-1045.7z","date":1658852847081},{"name":"20220726-1103.7z","date":1658854914269},{"name":"20220726-1223.7z","date":1658859757871},{"name":"20220726-1226.7z","date":1658859945446}]
```

**Tests**

   - A simple Joplin quit/restart today, got the same backup error message.
   - Quit > set all files to offline access > restart. Same error.

I was going to try changing the backup path, and when I checked Backup
settings I saw this:

![image](https://user-images.githubusercontent.com/2903411/181092117-ab4ccc0c-611d-41d4-ab78-0a7f91c3b65a.png)

However, the SQLite settings table does have the correct value:

![image](https://user-images.githubusercontent.com/2903411/181092138-a53dbdc5-9eee-4839-bca0-4e0d08251712.png)

So, test steps.

1. Copy all backups to  C:\Users\charl\Downloads\Joplin Backup
2. In Joplin, change backup path using copy/paste to C:\Users\charl\Downloads\Joplin Backup
3. Quit and restart
4. Check how path is displayed. OK.
    ![image](https://user-images.githubusercontent.com/2903411/181092196-f074ef53-0144-4660-a4dc-dd95296e444d.png)
5. Wait for on-startup backup. Get bizarre error message. What's with that path?
    ![image](https://user-images.githubusercontent.com/2903411/181092339-2674a7ca-2475-46ce-b067-5c429e7031b3.png)
6. What's in the database?
    ![image](https://user-images.githubusercontent.com/2903411/181092410-5d8f1063-440e-4646-b91d-6db42586e337.png)
7. On a whim, tried browsing to the backup folder and selecting it. This resulted, again, in the truncated path displayed. Database value is correct.
    ![image](https://user-images.githubusercontent.com/2903411/181092501-d3ea8f1b-e7b7-4a3d-81d4-24f80d005ae2.png)
8. Renamed the backup folder, removing spaces. Pasted in the new path. The path displays correctly, but is stored wrong.
    ![image](https://user-images.githubusercontent.com/2903411/181092579-430c9496-7962-46dd-8140-e43e9477bffc.png)
    ![image](https://user-images.githubusercontent.com/2903411/181092595-63c151a3-0812-4564-ba3b-5bfde79330bb.png)
9. Use the Browse button to select the path. This time all is correct.
    ![image](https://user-images.githubusercontent.com/2903411/181092650-e555ba8b-3e1d-449b-aed3-2487555a28b9.png)
10. Quit/restart. Same error!
    ![image](https://user-images.githubusercontent.com/2903411/181092681-c45dfda2-15f7-460c-9b46-1d7024ff46b0.png)

**Comment by JackGruber** [comment]
I think there a different bugs with the Folder selector. The first Bug I have logged.
https://github.com/laurent22/joplin/issues/6692

**Comment by bladewolf55** [comment]
I see the problem. SB is trying to delete a directory, but should be deleting a file. In the screenshot the command is 

`rmdir`

Should be 

`del` or some other delete command.

**Comment by JackGruber** [comment]
And a second issue with manual enterd path
https://github.com/laurent22/joplin/issues/6693

**Comment by JackGruber** [comment]
OK, the error for deleting the ZIP files is fixed, but for the problems with the manual enterd path oder path with space we need  a fix on the Joplin side.

**Comment by bladewolf55** [comment]
Oh, good news! I'll be looking for the plugin update to appear in Joplin and will apply and confirm back to you.

**Comment by bladewolf55** [comment]
Thanks, Jack! I installed the plugin manually. Seems to be working as expected, now.
