### ISSUE TITLE
moveFinishedBackup: dest already exists.

### ISSUE THREAD

**Issue by mo-han** [JackGruber/joplin-plugin-backup#48]
single backup, no sub-folder.
the first backup is fine, with two folders: `notes` & `profile`.
the next backup pops up this message, with a `joplin_active_backup_job` containing `notes` & `profile`, while the previous `notes` seems to prevent the new `notes` to moved in place.

**Comment by JackGruber** [comment]
Plz. provide the logfile `"~\.config\joplin-desktop\cache\io.github.jackgruber.backup\activeBackup.log"`

**Comment by mo-han** [comment]
@JackGruber 
only one single line in that log file
```
[2022-12-05 20:22:47.757] [error] moveFinishedBackup: dest already exists.
```

**Comment by JackGruber** [comment]
Ok this is a bug with `backupRetention = 1` and `RAW`/`MD Fontmatter` format.
Until a fix you can try set `Keep x backups` to a value bigger than 1 or Jex format.

**Comment by JackGruber** [comment]
Could you please test this version: [io.github.jackgruber.backup.zip](https://github.com/JackGruber/joplin-plugin-backup/files/10169998/io.github.jackgruber.backup.zip)

**Comment by mo-han** [comment]
> Could you please test this version: [io.github.jackgruber.backup.zip](https://github.com/JackGruber/joplin-plugin-backup/files/10169998/io.github.jackgruber.backup.zip)

fixed
