### ISSUE TITLE
showing backup progress notice

### ISSUE THREAD

**Issue by joochlee** [JackGruber/joplin-plugin-backup#49]
Hi, Thank you for valuable extension!

It is so helpful extension, but there is one thing missing...

sometimes, it is not easy to check whether it is working or not.
so could you add some notification or progress bar when it is working ?

It will be perfect extension if it is added! 👍

**Comment by JackGruber** [comment]
This is not possible, because Joplin provides not status bar for plugins: 
I already asked about this at the forum of Joplin, because my backup runs for about 20-30 minutes. 
When a error occurese, then an error message should pop up.
