### ISSUE TITLE
Explictly state backup path is the target and not the enclosing directory.

### ISSUE THREAD

**Issue by gallagherman** [JackGruber/joplin-plugin-backup#5]
I, a meek end-user, assumed the backup path behavior would create a joplin backup within the directory I used. So I specified a folder I keep my backups in. 

Example path I used on MacOS:
`/Users/gallagherman/dropbox/backup/`

I thought it would create something like `/Users/gallagherman/dropbox/backup/joplinbkup.jex` or something of the like.

However, I thought wrong. Joplin backup overwrote all the content in my backup folder!

I do think I was a bit careless, but I think it should be explicitly stated that the backup path is the exact backup target. It is too easy for a user to put the backup path to their home directory or something similar and overwrite everything!

**Comment by JackGruber** [comment]
Add hint in the documentary

**Comment by JackGruber** [comment]
Was mentioned in the documentation in the settings for Path.
