### ISSUE TITLE
active backup directory has to be renamed each time manually

### ISSUE THREAD

**Issue by stephenr-2** [JackGruber/joplin-plugin-backup#52]
The first two times it worked correctly. After checking, I renamed the target folder name and since then at each automatic backup the following error message comes and I have to rename the folder manually:
![20230608 Joplin Backup error message](https://github.com/JackGruber/joplin-plugin-backup/assets/135964517/c6a580e3-a051-4f88-867e-3781a93fae2a)
I have set the Keep x backups option to 7.

**Comment by JackGruber** [comment]
Please try a other destination as your Dropbox folder. Possible because dropbox is uploading files and has a lock on this files the rename is not possible.

**Comment by stephenr-2** [comment]
Thanks Jack for the tipp. I changed the backup destination to a local folder. Now it works well, both automatic and manual backup.

**Comment by stephenr-2** [comment]
Issue can be closed, I got the right tipp from Jack. It was not a bug of the backup plugin.

**Comment by JackGruber** [comment]
You can try to setup `Temporary export path` to a local folder and the `Backup Path` to your dropbox folder.
Than only the finished contend is copied and possibly this makes then no problems.
