### ISSUE TITLE
Automatic Backups Not Working in Linux Mint

### ISSUE THREAD

**Issue by pvstyps** [JackGruber/joplin-plugin-backup#54]
I've been using the Simple Backup plugin with Joplin for a while now on two different machines and it's been working great. I just added Joplin 2.11.11 to a third machine running Linux Mint 21.1 and the automatic backups don't seem to be working in this case. Manual backups do seem to work just fine, however. I've tried deleting and reinstalling the plugin but that didn't change anything, and I've also rebooted the computer and application several times and waited for a long time to see if an automatic backup would eventually be created, but nothing seems to work.

**Comment by JackGruber** [comment]
Could you please set the Loglevel to debug, run a manual backup and upload the log. 
The logfile is stored in the backup path.

**Comment by pvstyps** [comment]
I tried to do this, but there is no "Debug" option for the Loglevel. There is only Verbose, Info, Warning, and Error. I also tried each of these and none of them created a log file in the backup path.

I tried this on a Windows machine and it does make the log file just fine, so this is only happening on Linux Mint.

**Comment by JackGruber** [comment]
Ok, set it to `verbose` and enable the joplin [debuging mode ](https://joplinapp.org/debugging/#desktop-application).
Than do the same steps again and post the log file from joplin and during the backup run and check the following folder for a logfile: `~/.config/joplin-desktop/cache/io.github.jackgruber.hotfolder` during the backup and after.
Have you configured a `Temporary export path`? When yes, please check this path also for a logfile.

**Comment by pvstyps** [comment]
Okay, here are those log files.

[backup.log](https://github.com/JackGruber/joplin-plugin-backup/files/12319714/backup.log)
[log.txt](https://github.com/JackGruber/joplin-plugin-backup/files/12319715/log.txt)

**Comment by JackGruber** [comment]
Ok backups are only made when something has changed `Only on change` and when one hour has passed.
Configured this way on purpose?

**Comment by pvstyps** [comment]
I set it that way so I wouldn't have superfluous backups, but the problem is backups aren't being created even when changes are made. This function does work on my other computers.

**Comment by JackGruber** [comment]
We can try if we see more in the develop version of the plugin.

1. Uninstall the backup plugin
2. restart joplin
3. download the [backup_plugin_dev.zip](https://github.com/JackGruber/joplin-plugin-backup/files/12341474/backup_plugin_dev.zip) 
4. unzip the backup_plugin_dev.zip file
5. enter the path to the unzipted dev plugin in Joplin under Plugins -> Advanced Settings -> Development plugins
6. restart joplin

Now a new window with the debug console from the plugin should open.
Change a note and wait wait at least one hour. 
Copy alle the output from the debuge console in a file and uplode the file to the issue
