### ISSUE TITLE
Are notes history also backed up ?

### ISSUE THREAD

**Issue by benintech** [JackGruber/joplin-plugin-backup#55]
Are notes history also backed up ?
I think that's an information you could add to your FAQ section.

**Comment by JackGruber** [comment]
No the History/Revions are not included in the backup

**Comment by Perkolator** [comment]
> No the History/Revions are not included in the backup

Why not? The history/revisions are important data!

**Comment by JackGruber** [comment]
Since it is not supported by Joplin export.

**Comment by Perkolator** [comment]
Oh. That's really unfortunate. Guess I'll have to make my own script to zip+encrypt the .sqlite file myself.

OR, why couldn't your plugin backup/zip+encrypt the sqlite file?! Is it necessary to export for backup?
