### ISSUE TITLE
Which option to take for initial sync of Joplin on new iPhone?

### ISSUE THREAD

**Issue by stephenr-2** [JackGruber/joplin-plugin-backup#58]
Hi,
I use Joplin heavily and the initial sync on a 2nd iPhone some time ago took a long time overnight. I use the Dropbox sync.

Now I have a new iPhone and I see 2 options for installing and syncing Joplin on it:
1) I will use Apple quick start data transfer, so all apps with settings and data are transferred. That means all Joplin notebooks and notes will be on the new iPhone after tie quick start. My question: does the Joplin sync mechanism recognize that correctly or will there be sync conflicts with possible data loss?

2) I delete Joplin on the new iPhone after the quick start data transfer. Then I install it again and start an initial sync which probably will take some hours and I will have to monitor it.

Can you give me an advice which of the two options I should go for?

Many thanks in advance.
BR from Switzerland, 
Stephen

**Comment by JackGruber** [comment]
Sorry this has nothing to do with the Joplin Simple Backup plugin. 
Please ask the question on the Joplin forum. https://discourse.joplinapp.org/

**Comment by stephenr-2** [comment]
sorry, I was not a aware that I posted this on the plugin repository which is of course wrong.
