### ISSUE TITLE
Backup error when manually creating backup twice in a row in the same minute

### ISSUE THREAD

**Issue by redmorr** [JackGruber/joplin-plugin-backup#7]
Clicking `Create Backup` button twice in the same minute results in an error.

Button location:
![image](https://user-images.githubusercontent.com/19555512/108072541-52eae400-7067-11eb-8d77-d7cac8ddfc61.png)

My backup path after the error has occurred:
![image](https://user-images.githubusercontent.com/19555512/108072783-9c3b3380-7067-11eb-98dc-d0c3fbeabc04.png)

Joplin popup message after the second backup:
![image](https://user-images.githubusercontent.com/19555512/108072743-8d548100-7067-11eb-8f7a-9a612971c18b.png)

My backup settings:
![image](https://user-images.githubusercontent.com/19555512/108073300-2a171e80-7068-11eb-8971-c4ba07602684.png)

Log file attached:
[backup.log](https://github.com/JackGruber/joplin-plugin-backup/files/5989066/backup.log)

**Comment by JackGruber** [comment]
I do think I was a bit careless, but I think it should be explicitly stated that the backup path is the exact backup target. It is too easy for a user to put the backup path to their home directory or something similar and overwrite everything!

But this only occurs when you make several backups at the same minute.

**Comment by JackGruber** [comment]
accidentally closed
