### ISSUE TITLE
Suppress error: There is no Data to export 

### ISSUE THREAD

**Issue by JackGruber** [JackGruber/joplin-plugin-backup#71]
Suppress error message when automatically creating a backup if there is no data in the profile. 
![grafik](https://github.com/JackGruber/joplin-plugin-backup/assets/24863925/bab414c9-d6d5-4c73-8ae4-783c70430903)

See also https://github.com/laurent22/joplin/issues/10046

**Comment by personalizedrefrigerator** [comment]
Thank you for working on this!

With the latest version of the backup plugin (1.4.1 on Joplin 3.0.2), I'm still getting an error when attempting to create a backup, just after creating a new profile:

![screenshot: Backup error for jex: There is no data to export](https://github.com/JackGruber/joplin-plugin-backup/assets/46334387/419e5c27-ac32-4101-940d-824913a48781)

**Comment by JackGruber** [comment]
For a automatic backup, or is this from a manual? The error is only on a automatic backup suppresed.

**Comment by personalizedrefrigerator** [comment]
> For a automatic backup, or is this from a manual? The error is only on a automatic backup suppresed.

This was a manual backup. (Ignore the issue raised above!)
