### ISSUE TITLE
Option to back up only changed notebooks?

### ISSUE THREAD

**Issue by tomasz1986** [JackGruber/joplin-plugin-backup#72]
Please forgive me if the question has been asked before, but would it be difficult to implement an option to back up only changed notebooks? Currently, when using the "only on change" backup type, the plugin still exports all notebooks to JEX even if only some of them have actually changed since the last backup.

The reason for this is to reduce the backup size.

**Comment by JackGruber** [comment]
Yes, this is the desired behavior from `only on change`, a backup is not always created at the specified time interval, but only if there has been a change. 

This would only be possible if each note is exported individually, but then a complete import would no longer be possible and you have to import every note for its self, and all internal links would be lost and the folder structures.

**Comment by tomasz1986** [comment]
What I mean is that let's say I've got 20 notebooks and I make a backup. The initial backup contains all of those 20 notebooks. Then I edit just a single note in one of the notebooks. Then I do yet another backup. The new backup still contains all 20 notebooks, even though in reality the "change" was in a single note in only one of those notebooks.

Is it still required to always back up all notebooks in such a situation?

**Comment by JackGruber** [comment]
Yes it`s required to always back up all notebooks. 

Each note gets a new ID during the import and therefore duplicates are created and the links between the notes are lost

The following will happen when not:

You have the following:

- `Note A` in `Notebook A`
- `Note B` in `Notebook B`
- Create First Backup (Contains all infos) `Backup A`
- Edit `Note A` 
- Create Backup (Contains only `Note A`) `Backup B`
- Start a new Joplin
- Import `Backup A` and `Backup B`
- You have now the following:
- `Note A` in `Notebook A` from `Backup A`
- `Note B` in `Notebook B` from `Backup A`
- `Note B` in `Notebook X` from `Backup B`

The `Note B` was is now available twice with different contents.

**Comment by tomasz1986** [comment]
I see… Thank you for the explanation!

I originally enabled the per-notebook backup to save space, but this means that there is basically no difference in size when compared to a single JEX backup, right?

**Comment by JackGruber** [comment]
Correct, the option is only that a full export is created when some note, notebook, tag or resource has changed.
