### ISSUE TITLE
My Backup process is stopped by a non-exisiting

### ISSUE THREAD

**Issue by chungyan5** [JackGruber/joplin-plugin-backup#73]
Hi, 

I enable the verbose log of the backup process and find the backup process is stopped like below which stop at a "Project" notebook, but i do not have this notebook in my current notebooks list. I cannot find any further error, just stop there and non-complete my backup. Could you please give me some hints to troubleshoot it or how to remove this non-exisiting notebook? 

![image](https://github.com/JackGruber/joplin-plugin-backup/assets/780701/58ac7230-8752-4121-bddc-74fb57a9708b)

**Comment by JackGruber** [comment]
The Joplin API returns a notebook `Projects`, you can search in Joplin with `notebook:Project` for this Notebook.
Works the backup with the option `Single JEX` ?

**Comment by chungyan5** [comment]
> notebook:Project

Thanks for this hint, i find out TWO duplciated notes by this command(i am not sure what is the reason to have these two same notes), i must removed TWO of them, then backup is working again. However, cannot find the reason and what happens to that two same notes.
