### ISSUE TITLE
Partially German description in Backup settings

### ISSUE THREAD

**Issue by pihentagy** [JackGruber/joplin-plugin-backup#74]
![image](https://github.com/JackGruber/joplin-plugin-backup/assets/29916/94c513dc-a4bf-46f3-b583-1e4c53154315)

**Comment by JackGruber** [comment]
- Translation error in en_EN

**Comment by pihentagy** [comment]
Another issue is that it states, that the selected path is exclusively for Joplin. But that is not true. There will be a `JoplinBackup` directory created under that dir, and only that subdir is for Joplin only.

Shouldn't 'Browse...' open a file browser on the selected path's `JoplinBackup` dir?

**Comment by JackGruber** [comment]
It is true

> Storage location for the backups. This path is exclusively for the Joplin Backups if the settings for 'Create a subfolder' are deactivated, no other data should be in it!
