### ISSUE TITLE
use the backup file generated by the plugin to restore a complete Joplin environment

### ISSUE THREAD

**Issue by ajay-gh** [JackGruber/joplin-plugin-backup#8]
Since the plug-in does back-up more than just the notes (settings etc.), assume you want to use it later to reconfigure Joplin on a different computer, or on the same computer after some problem. So you install a fresh copy of Joplin, and you have the backup file in front of you. What next ?
Am I just missing instructions, or is all I have to do import the JEX file (including all settings etc.) ?
The descriptions don't seem to address this "typical user problem".

**Comment by JackGruber** [comment]
No athe the moment no settings are backuped!

**What is backuped**
-  Notebooks as JEX export (empty notbooks are not backed up)
-  The keymap-desktop.json
-  The userchrome.css
-  The userstyle.css
-  The templates folder

Those who use coustum css know how to restore this files, but in short, copy the file back to `.config\joplin-desktop`
The templates are restored as they were created.
For the keymap-desktop.json you can restore them by overwriting the keymap-desktop.json in `.config\joplin-desktop`.

For the settings i still hope for a backup restore function, which has to be provided by joplin. 

https://discourse.joplinapp.org/t/export-import-settings/14668/3

But you are right, I improve the documentation with a restore section.
