### ISSUE TITLE
Dropbox Backup

### ISSUE THREAD

**Issue by kelvinkad** [JackGruber/joplin-plugin-backup#80]
Is it possible to make notes titles legible (preferably with the exact title name I created the note on Joplin)?
The backup plugin renames them to a random name, this way is very complicated to locate some specific note I'd like to save as a single file in my PC or send someone.

**Comment by JackGruber** [comment]
If `RAW` is selected as the `Export format`, this is completely normal, as this is the Joplin RAW data. `MD frontmatter` can still be selected and Joplin will create files with the note names.

**Comment by kelvinkad** [comment]
Where can I find this setting? I tried and didn't find it

**Comment by JackGruber** [comment]
This Plugin is not availabile for Andorid, only Desktop. I thonk you are using the Sync and the Sync is no Backup and has nothin to do with this Plugin.

**Comment by kelvinkad** [comment]
Yes, I mean the sync plugin, sorry about that.
So it's not possible to sync to dropbox with the normal title of the notes instead of the random titles?
