### ISSUE TITLE
explain or adapt function of "create backup" menu command

### ISSUE THREAD

**Issue by ajay-gh** [JackGruber/joplin-plugin-backup#9]
Depending on the developers intentions, I suggest to do one of the following two:

- explain in the documentaion whether the "create backup" command in the tools menu (added there when the plugin is installed) respects the options set for the plugin. Example: with "only on change" set, when the tool menu command is evoked, is an extra backup created anyway, or only if a change was detected.
- consider (and implemented) how the tool menu command should operate given the options available in the plugin's settings.
My suggestion how to use the options already set:
- do respect "single jex" flag
- do NOT respect "keep x backup"
- ignore interval (I suppose it's already the case)
- BUT ignore "only on change"
- AND present a file open dialog box in order to let the user choose a file path different from the default path.
The later would be very useful in case the default backup path is on a drive not always connected to the device.

Just my 2 bit contribution. Thanks

**Comment by JackGruber** [comment]
A manual backup in which the settings can be changed will currently not be available. 
See updatet documentation.
